require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Capybara/FeatureMethods:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - pusher-fake.gemspec
    - bin/pusher-fake
    - spec/**/*_spec.rb

Metrics/LineLength:
  Exclude:
    - bin/pusher-fake

Naming/FileName:
  Exclude:
    - lib/pusher-fake.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "()"

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes
