require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Exclude:
    - bin/pusher-fake

Metrics/BlockLength:
  Exclude:
    - pusher-fake.gemspec
    - bin/pusher-fake
    - spec/**/*_spec.rb

Naming/FileName:
  Exclude:
    - lib/pusher-fake.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "()"

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes
